name: AI Design Agent (daily)

on:
  schedule:
    - cron: "0 7 * * *"   # joka päivä 07:00 UTC (~09:00 Helsinki)
  workflow_dispatch:       # mahdollisuus ajaa käsin GitHubin napista

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m src.main